#!/bin/sh
# Starts shadowsocks

MYDIR=`dirname $0`

ss_local_port=12345
ss_server_ip=52.197.156.235
ss_server_port=17989

verb=$1

echo $verb
if [[ "$verb" == "stop" ]]; then
	$MYDIR/ss-rules -f	
	
	if [[ -f /var/run/shadowsocks.pid ]]; then
		killall ss-redir
	fi

	echo "VPN stopped"
	exit 0
fi

if [[ "$verb" == "start" ]]; then
	if [[ -f $MYDIR/chnroute.txt ]]; then
		echo "Using chnroute.txt to bypass VPN for China local addresses"
		CHNROUTE="-i $MYDIR/chnroute.txt"
	fi

	ss-redir -v \
		-c $MYDIR/ss-redir.json \
		-s $ss_server_ip \
		-p $ss_server_port \
		-l $ss_local_port \
		-f /var/run/shadowsocks.pid &
	$MYDIR/ss-rules -s $ss_server_ip -l $ss_local_port $CHNROUTE

	echo "VPN started on port $ss_local_port"
	exit 0
fi

echo "Usage: ss (start|stop)"
