#!/bin/sh
# Starts shadowsocks

ss_local_port=12345
ss_server_ip1=52.197.156.235
#ss_server_ip2=52.193.77.21

verb=$1

echo $verb
if [[ "$verb" == "stop" ]]; then
	./ss-rules -f	
	
	if [[ -f /var/run/shadowsocks.pid ]]; then
		killall ss-redir
	fi

	echo "VPN stopped"
	exit 0
fi

if [[ "$verb" == "start" ]]; then
	if [[ -f chnroutes.txt ]]; then
		echo "Using chnroutes.txt to bypass VPN for China local addresses"
		CHNROUTES="-i chnroutes.txt"
	fi

	ss-redir -v -c ss-redir.json -f /var/run/shadowsocks.pid &
	./ss-rules -s $ss_server_ip1 -l $ss_local_port $CHNROUTES

	echo "VPN started"
	exit 0
fi

echo "Usage: ss (start|stop)"
