#!/bin/sh
# Starts shadowsocks

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

ss_local_port=12345
ss_server_ip1=52.197.156.235
#ss_server_ip2=52.193.77.21

verb=$1

echo $verb
if [[ "$verb" == "stop" ]]; then
	$MYDIR/ss-rules -f	
	
	if [[ -f /var/run/shadowsocks.pid ]]; then
		killall ss-redir
	fi

	echo "VPN stopped"
	exit 0
fi

if [[ "$verb" == "start" ]]; then
	if [[ -f $MYDIR/cnroute.txt ]]; then
		echo "Using cnroute.txt to bypass VPN for China local addresses"
		CNROUTE="-i $MYDIR/cnroute.txt"
	fi

	ss-redir -v -c $MYDIR/ss-redir.json -f /var/run/shadowsocks.pid &
	$MYDIR/ss-rules -s $ss_server_ip1 -l $ss_local_port $CNROUTE

	echo "VPN started"
	exit 0
fi

echo "Usage: ss (start|stop)"
