#!/bin/sh
#
# Copyright (C) 2016 Jian Chang <aa65535@live.com>
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#
# Modifications for the AsusWRT-Merlin firmware by Mike Fischer
# Original at https://github.com/shadowsocks/luci-app-shadowsocks
#

usage() {
	cat <<-EOF
		Usage: ss-rules [options]

		Valid options are:

		    -s <server_ips>         ip address of shadowsocks remote server
		    -l <local_port>         port number of shadowsocks local server
		    -S <server_ips>         ip address of shadowsocks remote UDP server
		    -L <local_port>         port number of shadowsocks local UDP server
		    -i <ip_list_file>       a file whose content is bypassed ip list
		    -b <wan_ips>            wan ip of will be bypassed
		    -w <wan_ips>            wan ip of will be forwarded
		    -I <interface>          proxy only for the given interface
		    -d <target>             the default target of lan access control
		    -a <lan_hosts>          lan ip of access control, need a prefix to
		                            define proxy type
		    -e <extra_options>      extra options for iptables
		    -o                      apply the rules to the OUTPUT chain
		    -O                      apply the global rules to the OUTPUT chain
		    -u                      enable udprelay mode, TPROXY is required
		    -U                      enable udprelay mode, using different IP
		                            and ports for TCP and UDP
		    -f                      flush the rules
		    -h                      show this help message and exit
EOF
	exit $1
}

loger() {
	# 1.alert 2.crit 3.err 4.warn 5.notice 6.info 7.debug
	logger -st ss-rules[$$] -p$1 $2
}

flush_rules() {
	iptables-save -c | grep -v "SS_SPEC" | iptables-restore -c
	if which ip >/dev/null 2>&1; then
		set +e
		ip rule del fwmark 1 lookup 100 2>/dev/null
		ip route del local default dev lo table 100 2>/dev/null
		set -e
	fi
	for setname in $(ipset --list | grep "ss_spec" | sed "s/Name: \(.*\)/\1/"); do
		ipset --destroy $setname
	done
	# UCI is OpenWRT-specfic, so it can't be used here.  Anyway, this setting appears
	# to be to allow the shadowsocks binary through the firewall, which isn't relevant
	# to AsusWRT-Merlin anyway.
	#FWI=$(uci get firewall.shadowsocks.path 2>/dev/null)
	#[ -n "$FWI" ] && echo '# firewall include file' >$FWI
	return 0
}

ipset_init() {
	# man page for old version of ipset:
	# https://people.netfilter.org/kadlec/ipset/ipset.man.html

	# Note that order matters here. All IPs/netmasks inside a set must be added to the set
	# immediately after it's created and before any other sets are created.
	ipset --restore <<-EOF || return 1
		-N ss_spec_src_ac nethash --hashsize 64
		-N ss_spec_src_bp nethash --hashsize 64
		-N ss_spec_src_fw nethash --hashsize 64
		-N ss_spec_dst_sp iphash --hashsize 64
		$(gen_special_purpose_ip | sed -e "s/^/-A ss_spec_dst_sp /")
		-N ss_spec_dst_sp_mask nethash --hashsize 64
		$(gen_special_purpose_mask | sed -e "s/^/-A ss_spec_dst_sp_mask /")
		-N ss_spec_dst_bp nethash --hashsize 10000
		$(sed -e "s/^/-A ss_spec_dst_bp /" ${IGNORED:=/dev/null} 2>/dev/null)
		$(for ip in $WAN_BP_IP; do echo "-A ss_spec_dst_bp $ip"; done)
		-N ss_spec_dst_fw nethash --hashsize 64
		$(for ip in $WAN_FW_IP; do echo "-A ss_spec_dst_fw $ip"; done)
		COMMIT
EOF

	# Because of the ordering issue, more work is required to support this setting.
	# Wait until it's needed.
	#	$(gen_lan_host_ipset_entry)

	return 0
}

# Different routers have different iptables syntax
# From https://github.com/RMerl/asuswrt-merlin/wiki/Using-ipset
case $(uname -m) in
  armv7l)
    MATCH_SET='--match-set'
    ;;
  mips)
    MATCH_SET='--set'
    ;;
esac

ipt_nat() {
	include_ac_rules nat
	ipt="iptables -t nat"
	$ipt -A SS_SPEC_WAN_FW -p tcp \
		-j REDIRECT --to-ports $local_port || return 1
	if [ -n "$OUTPUT" ]; then
		$ipt -N SS_SPEC_WAN_DG
		$ipt -A SS_SPEC_WAN_DG -m set $MATCH_SET ss_spec_dst_sp dst -j RETURN
		$ipt -A SS_SPEC_WAN_DG -m set $MATCH_SET ss_spec_dst_sp_mask dst -j RETURN
		$ipt -A SS_SPEC_WAN_DG -p tcp $EXT_ARGS -j $OUTPUT
		$ipt -I OUTPUT 1 -p tcp -j SS_SPEC_WAN_DG
	fi
	return $?
}

ipt_mangle() {
	[ -n "$TPROXY" ] || return 0
	if !(lsmod | grep -q TPROXY && which ip >/dev/null); then
		loger 4 "TPROXY or ip not found."
		return 0
	fi
	ip rule add fwmark 1 lookup 100
	ip route add local default dev lo table 100
	include_ac_rules mangle
	iptables -t mangle -A SS_SPEC_WAN_FW -p udp \
		-j TPROXY --on-port $LOCAL_PORT --tproxy-mark 0x01/0x01
	return $?
}

export_ipt_rules() {
	[ -n "$FWI" ] || return 0
	cat <<-CAT >>$FWI
	iptables-restore -n <<-EOF
	$(iptables-save | grep -E "SS_SPEC|^\*|^COMMIT" |\
			sed -e "s/^-A \(OUTPUT\|PREROUTING\)/-I \1 1/")
	EOF
CAT
	return $?
}

gen_lan_host_ipset_entry() {
	for host in $LAN_HOSTS; do
		case "${host:0:1}" in
			n|N)
				echo -A ss_spec_src_ac ${host:2}
				;;
			b|B)
				echo -A ss_spec_src_bp ${host:2}
				;;
			g|G)
				echo -A ss_spec_src_fw ${host:2}
				;;
		esac
	done
}

gen_special_purpose_ip() {
	cat <<-EOF | grep -E "^([0-9]{1,3}\.){3}[0-9]{1,3}"
		255.255.255.255
		8.8.8.8
		$server
		$SERVER
EOF
}

gen_special_purpose_mask() {
	cat <<-EOF | grep -E "^([0-9]{1,3}\.){3}[0-9]{1,3}"
		0.0.0.0/8
		10.0.0.0/8
		100.64.0.0/10
		127.0.0.0/8
		169.254.0.0/16
		172.16.0.0/12
		192.0.0.0/24
		192.0.2.0/24
		192.31.196.0/24
		192.52.193.0/24
		192.88.99.0/24
		192.168.0.0/16
		192.175.48.0/24
		198.18.0.0/15
		198.51.100.0/24
		203.0.113.0/24
		224.0.0.0/4
		240.0.0.0/4
EOF
}

include_ac_rules() {
	local protocol=$([ "$1" = "mangle" ] && echo udp || echo tcp)
	iptables-restore -n <<-EOF
	*$1
	:SS_SPEC_LAN_DG - [0:0]
	:SS_SPEC_LAN_AC - [0:0]
	:SS_SPEC_WAN_AC - [0:0]
	:SS_SPEC_WAN_FW - [0:0]
	-A SS_SPEC_LAN_DG -m set $MATCH_SET ss_spec_dst_sp dst -j RETURN
	-A SS_SPEC_LAN_DG -m set $MATCH_SET ss_spec_dst_sp_mask dst -j RETURN
	-A SS_SPEC_LAN_DG -p $protocol $EXT_ARGS -j SS_SPEC_LAN_AC
	-A SS_SPEC_LAN_AC -m set $MATCH_SET ss_spec_src_bp src -j RETURN
	-A SS_SPEC_LAN_AC -m set $MATCH_SET ss_spec_src_fw src -j SS_SPEC_WAN_FW
	-A SS_SPEC_LAN_AC -m set $MATCH_SET ss_spec_src_ac src -j SS_SPEC_WAN_AC
	-A SS_SPEC_LAN_AC -j ${LAN_TARGET:=SS_SPEC_WAN_AC}
	-A SS_SPEC_WAN_AC -m set $MATCH_SET ss_spec_dst_fw dst -j SS_SPEC_WAN_FW
	-A SS_SPEC_WAN_AC -m set $MATCH_SET ss_spec_dst_bp dst -j RETURN
	-A SS_SPEC_WAN_AC -j SS_SPEC_WAN_FW
	$(gen_prerouting_rules $protocol)
	COMMIT
EOF
}

gen_prerouting_rules() {
	[ -z "$IFNAMES" ] && echo -I PREROUTING 1 -p $1 -j SS_SPEC_LAN_DG
	for ifname in $IFNAMES; do
		echo -I PREROUTING 1 -i $ifname -p $1 -j SS_SPEC_LAN_DG
	done
}


#
# main
#
set -e

TEMP=$(getopt -o :s:l:S:L:i:b:w:I:d:a:e:oOuUfh -- "$@")
eval set -- "$TEMP"

while true; do
	case "$1" in
		-s)
			server=$(for ip in $2; do echo $ip; done)
			shift 2
			;;
		-l)
			local_port=$2
			shift 2
			;;
		-S)
			SERVER=$(for ip in $2; do echo $ip; done)
			shift 2
			;;
		-L)
			LOCAL_PORT=$2
			shift 2
			;;
		-i)
			IGNORED=$2
			shift 2
			;;
		-b)
			WAN_BP_IP=$2
			shift 2
			;;
		-w)
			WAN_FW_IP=$2
			shift 2
			;;
		-I)
			IFNAMES=$2
			shift 2
			;;
		-d)
			LAN_TARGET=$2
			shift 2
			;;
		-a)
			echo "Sorry, this option isn't currently supported."
			exit 128
			LAN_HOSTS=$2
			shift 2
			;;
		-e)
			EXT_ARGS=$2
			shift 2
			;;
		-o)
			OUTPUT=SS_SPEC_WAN_AC
			shift
			;;
		-O)
			OUTPUT=SS_SPEC_WAN_FW
			shift
			;;
		-u)
			TPROXY=1
			shift
			;;
		-U)
			TPROXY=2
			shift
			;;
		-f)
			flush_rules
			exit 0
			;;
		-h)
			usage 0
			;;
		--)
			shift
			break
			;;
	esac
done

[ -z "$server" -o -z "$local_port" ] && usage 2

if [ "$TPROXY" = 1 ]; then
	unset SERVER
	LOCAL_PORT=$local_port
elif [ "$TPROXY" = 2 ]; then
	: ${SERVER:?"You must assign an ip for the udp relay server."}
	: ${LOCAL_PORT:?"You must assign a port for the udp relay server."}
fi

flush_rules && ipset_init && ipt_nat && ipt_mangle && export_ipt_rules
RET=$?
[ "$RET" = 0 ] || loger 3 "Start failed!"
exit $RET
